CREATE TABLE PROJECT (
PROJ_ID INT AUTO_INCREMENT PRIMARY KEY,
PROJ_NM VARCHAR(50) NOT NULL,
PROJ_MNG VARCHAR(30) NOT NULL 

);

CREATE TABLE WORDDICT (
WORD_ID INT AUTO_INCREMENT PRIMARY KEY,
PROJ_ID INT NOT NULL,
WORD_KOR VARCHAR(50) NOT NULL,
WORD_ENG VARCHAR(50) NOT NULL,
WORD_ABR VARCHAR(50) NOT NULL,
WORD_DEF VARCHAR(2048),

FOREIGN KEY (PROJ_ID) REFERENCES PROJECT(PROJ_ID) ON DELETE CASCADE

);

ALTER TABLE project AUTO_INCREMENT=1;
ALTER TABLE worddict AUTO_INCREMENT=1;

INSERT INTO worddict( proj_id, word_kor, word_eng, word_abr, word_def)
VALUES(1,'한글','korean','kor','한국어');


SELECT PROJ_ID, PROJ_NM, PROJ_MNG 
FROM PROJECT

SELECT * FROM project;

INSERT INTO project(proj_nm, proj_mng)
VALUES('test3', 'tester');


SELECT * FROM worddict;

SELECT WORD_ID, PROJ_ID, WORD_KOR, WORD_ENG, WORD_ABR, WORD_DEF  
FROM   WORDDICT

SELECT * FROM worddict;

DROP TABLE WORDDICT;

DELETE from worddict;